siteName: 30 Reasons
siteDescription: 30 Reasons is a 30-poster campaign encouraging voters to support Hillary Clinton for President.
siteUrl: http://www.30reasons.org/
baseUrl: http://www.30reasons.org/

# Exclude and include
exclude: [30reasons.bbprojectd, static-templates]

# Collections
collections:
  reasons:
    output: true
    permalink: /reasons/:path/